services:
  wallos:
    container_name: wallos
    image: bellamy/wallos:latest
    ports:
      - "$PORT:80/tcp"
    environment:
      TZ: 'America/Toronto'
      PORT: $PORT
      HOST: 0.0.0.0
    # Volumes store your data between container upgrades
    volumes:
      - '/var/lib/wallos/db:/var/www/html/db'
      - './logos:/var/www/html/images/uploads/logos'
    restart: unless-stopped
